name: Build & Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy files
        run: |
          mkdir -p /home/abisek/blog-nextjs-crud
          rsync -a --delete \
            --exclude='.env' \
            ./ /home/abisek/blog-nextjs-crud/

      - name: Copy environment
        run: |
          cp /opt/.env /home/abisek/blog-nextjs-crud/.env

      - name: Install node modules
        working-directory: /home/abisek/blog-nextjs-crud
        run: npm ci

      - name: Build
        run: npm run build

      - name: Start application
        run: npm run start
